# Generated by Django 2.1b1 on 2018-07-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
	migrations.RenameField('Girl', 'girl_name', 'name'),
	migrations.RenameField('Girl', 'girl_age', 'age'),
    ]
